name: Deploy API on Code Changes

on:
  push:
    paths:
      - 'backend/api_heavy/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Uvicorn
      working-directory: ./backend/api_heavy
      run: nohup uvicorn main:app --host 0.0.0.0 --port 8000
